### ISSUE TITLE
Example Broken

### ISSUE THREAD

**Issue by yspreen** [mnater/Hyphenopoly#25] opened 2018-06-01 16:07 UTC
The example does not break on latest Chrome.

![image](https://user-images.githubusercontent.com/12631527/40851136-aff8f226-65c6-11e8-8815-3c75d7c78786.png)

**Comment by mnater** [comment] 2018-06-01 21:52
I can not reproduce the issue here.
May this be caused by issue #24?

If not:
What exact version of Chrome did you use (I tested with stable:67.0.3396.62 and  canary:69.0.3447.2)?
Which OS? (I tested on OS X and Windows 10)

Please reopen the issue if this has not been fixed with the fix for #24.

Thanks,
Mathias

**Closed as completed by mnater** 2018-06-01 21:52 UTC

**Comment by yspreen** [comment] 2018-06-06 11:52
Appears to be fine now

**Comment by mnater** [comment] 2018-06-06 16:07
Thank you
