### ISSUE TITLE
[Request] Pattern update for PTBR

### ISSUE THREAD

**Issue by andremacola** [mnater/Hyphenopoly#31] opened 2018-09-07 06:25 UTC
Hi,

What version of PT pattern do you use in this repo? I did some testing and the PT pattern do not work properly with ptbr, I just founded an updated version [here](http://linorg.usp.br/CTAN/language/hyph-utf8/tex/generic/hyph-utf8/patterns/tex/hyph-pt.tex) or in the babelpdf package for tex.

I'm a very new with TEX, so how do you compile the .tex file to hpb?

**Comment by andremacola** [comment] 2018-09-07 06:57
I created a pt-br pattern that works awesome based on the previous link. Can I create a pull request?

**Comment by mnater** [comment] 2018-09-07 09:27
Hi

Thank you for your contribution.
I used the patterns from https://github.com/hyphenation/tex-hyphen/blob/master/hyph-utf8/tex/generic/hyph-utf8/patterns/tex/hyph-pt.tex which seem to be the same as the patterns you linked.

So I wonder what didn't work exactly?

Is it just the name `pt.hpb` vs. `pt-br.hpb`?

In this case please see https://github.com/mnater/Hyphenopoly/wiki/Global-Hyphenopoly-Object#fallbacks

Or are there errors when hyphenating?
- Are the hyphenation rules for pt-br the same as for pt-pt?
- what words get hyphenated wrongly (could you give some examples)?

Best regards,
Mathias

**Comment by mnater** [comment] 2018-09-07 09:30
Oh! I was interrupted while answering and didn't see your second post.

Sure! Pull requests are always welcome ;-) Look's like you managed to convert from .tex to .hpb

**Comment by mnater** [comment] 2018-09-07 21:38
Currently looks like a duplicate of https://github.com/mnater/Hyphenopoly/issues/29

**Closed as completed by mnater** 2018-09-07 21:38 UTC
Labels: duplicate
