### ISSUE TITLE
IOS9 eachKey bug

### ISSUE THREAD

**Issue by Bertijn** [mnater/Hyphenopoly#88] opened 2019-09-04 09:55 UTC
Hi,

For my project we implemented the Hyphenopoly library, and after some intensive testing, we came across the error about 'const' and 'let' not being supported in 'strict' mode on IOS9 (there has been logged a ticket before).

After running the files (Hyphenopoly.js and Hyphenopoly_Loader.js) through Babel, the error about the const's were gone, but we occured a new error. In the 'checkCSSHyphensSupport(elm)' function, we got the error that elm.style was undefined.

After a lot of debugging, we noticed that where the function gets called (in a for-loop), the eachKey behaves rather weird in IOS9. 

````javascript
var nl = testContainer.getElementsByTagName("div");
eachKey(nl, function eachNode(n) {
        /* eslint-disable security/detect-object-injection */
        if (checkCSSHyphensSupport(nl[n]) && nl[n].offsetHeight > 12) {
            H.cf.langs[nl[n].lang] = "CSS";
        } else {
           loadPattern(nl[n].lang);
        }
        /* eslint-enable security/detect-object-injection */
});
````

We noticed that `nl[n]` in the loop was not only 2 divs, but also the number 2. This happened because `n`, the keys of the `nl` array, was 0, 1 and 'length'. Apparently IOS9 includes the 'length' as a key as well.

A quick fix for our project was adding the following condition:

````javascript
var nl = testContainer.getElementsByTagName("div");
    eachKey(nl, function eachNode(n) {
        if (n !== 'lenght') {
            /* eslint-disable security/detect-object-injection */
            if (checkCSSHyphensSupport(nl[n]) && nl[n].offsetHeight > 12) {
                H.cf.langs[nl[n].lang] = "CSS";
            } else {
               loadPattern(nl[n].lang);
            }
            /* eslint-enable security/detect-object-injection */
        }
});
````

I thought you might want to fix that in your code (maybe in a more robust way).

Kind regards,
Bertijn

**Comment by mnater** [comment] 2019-09-04 20:57
Hi

Thanks for the debugging work.

Sadly, I don't have an iOS9 device at hand anymore. I'm going to try to reproduce the issue in a Xcode simulator.

Anyhow, my code is fishy. `getElementsByTagName` returns a `HTMLCollection` but the code looks like it expected a `NodeList`. Maybe using `querySelectorAll` (wich returns a `NodeList`) and then doing a `foreach` over the `NodeList` would be a better approach.

Kindly,
Mathias

**Comment by mnater** [comment] 2019-09-06 03:01
Reproduced and fixed in develop branch (https://github.com/mnater/Hyphenopoly/commit/35ca3cf0519ff3f532933de7ca0e32465b0cf094#diff-e21a372b907c129ba216619c03fcbc38)

Will be part of the next release.

**Closed as completed** 2019-10-14 19:38 UTC
Labels: bug
